// Code generated by mockery 2.9.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

// InvokeEndpoint provides a mock function with given fields: method, endpoint, body
func (_m *Client) InvokeEndpoint(method string, endpoint string, body interface{}) error {
	ret := _m.Called(method, endpoint, body)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, interface{}) error); ok {
		r0 = rf(method, endpoint, body)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
